config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'
    get 'static_pages/contact'
    get "search(/:search)", to: "searches#index", as: :search
    devise_for :users, skip: :omniauth_callbacks,controller: {registrations: "registrations"}
    resources :users, only: [:show] do
      member do
        get :following
      end
    end
    resources :categories
    resources :mangas do
      resources :comments,only: [:create, :destroy]
      member do
        get :followers
      end
      resources :vote_mangas, only: [:create, :destroy]
    end
    resources :chapters do
      resources :votes,only: [:create,:destroy]
    end
    resources :authors
    resources :relationships, only: [:create, :destroy]
    namespace :admin do
      root "admin#index",as: :root
      resources :categories
      resources :mangas
      resources :chapters
      resources :animes
      resources :users do
        collection do
          post :import
        end
      end
    end
  end
  match '*.path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one :anime
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :chapters
  has_many :composes
  has_many :authors, through: :composes
  has_many :manga_categories
  has_many :categories,through: :manga_categories
  has_many :passive_relationships, class_name:  Relationship.name,
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  scope :order_manga, -> {order created_at: :desc}
  scope :most_view, -> {order number_of_read: :desc}
  scope :top_rate, -> {order average_rate: :desc}
  ratyrate_rateable "rate_manga", "rate_chapter"
  acts_as_votable
  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :poster, ThumbnailUploader

  def overall_ratings(manga)
    array = Rate.rateable
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
   def avg_rating_dimension_rate_manga(manga)
    array = Rate.rateable.dimensions
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
end

app/models/supports/manga.rb
class Supports::Manga
  attr_reader :manga, :mangas
    
  def initialize manga
    @manga = manga
  end
    
  def mangas
    @mangas ||= Manga.all
  end
    
  def comment_params
    @comment = Comment.new
  end
    
  def comments_tree
    @comments = @manga.comments
  end
end

app/controllers/admin/mangas_controller.rb
class Admin::MangasController < Admin::AdminController
  before_action :find_manga, only: [:edit, :update, :show, :destroy]
  load_and_authorize_resource

  def index
    @mangas = Manga.order_manga.paginate page: params[:page], per_page: Settings.mangas.page
  end

  def show
  end

  def new
    @manga = Manga.new
  end

  def create
    @manga = Manga.new manga_params
    if @manga.save
      flash[:info] = t("manga_created")
      redirect_to admin_mangas_path
    else
      flash[:alert] = t("manga_creating_error")
      render :new
    end
  end

  def edit
  end

  def update
    if @manga.update manga_params
      flash[:alert] = t("manga_updated")
      redirect_to admin_mangas_path
    else
      flash[:alert] = t("manga_creating_error")
      render :edit
    end
  end

  def destroy
    if @manga.destroy
      flash[:success] = t(".mangas_deleted")
      redirect_to admin_mangas_path
    else
      flash[:danger] = t(".mangas_not_deleted")
      render :index
    end
  end

  private

  def manga_params
    params.require(:manga).permit(:name, :detail, :poster,
      :poster_cache, :thumbnail, :thumbnail_cache, :country, category_ids: [])
  end

  def find_manga
    @manga = Manga.find_by id: params[:id]
    redirect_to admin_mangas_path if @manga.nil?
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :get_manga, only: [:show]

  def index
    @mangas = Manga.order_manga
    q = params[:search]
    if q
      @mangas = Manga.search(name_cont: q).result
    else
      @mangas = Manga.order_manga
    end
  end

  def show
    @chapters = @manga.chapters.order("LENGTH(name)").order(:name)
    @authors = @manga.authors.all
    @categories = @manga.categories.order(:name)
    @supports = Supports::Manga.new @manga
    @comment = Comment.new
    @comments = @manga.comments.hash_tree
    Manga.increment_counter(:number_of_read, @manga.id)
  end

  private
  def get_manga
    @manga = Manga.find_by id: params[:id]
    if @manga.nil?
      redirect_to root_url
    end
  end
end

app/helpers/manga_helper.rb
module MangaHelper
end

app/views/mangas/_author.html.erb
<%= link_to author.name, author_path(author) %>

app/views/mangas/_chapter.html.erb
<ul>
  <li class="row">
    <div class="col-xs-5 chapter">
      <%= link_to chapter.name, chapter_path(chapter) %>
    </div>
    <div class="col-xs-4 text-center small"><%= l(chapter.updated_at, format: :dmy) %></div>
  </li>
</ul>

app/views/mangas/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @manga.id %></div>
    <%= f.submit t(".follow"), class: "btn btn-primary" %>
  <div>
    <%= t(".followed") %> : <%= @manga.followers.count %> <%= t(".users") %>
  </div>
<% end %>

app/views/mangas/_manga.html.erb
<div class="container">
  <div class="row">
    <div class="center-side col-md-8">
      <div class="items">
        <div class="row">
          <div class="item">
            <figure class="clearfix">
              <div class="image">
                <!-- <img src="//st.nettruyen.com/Data/logos/logo-nettruyen.png" class="lazy" data-original="https://3.bp.blogspot.com/-U9YzPttwuiA/W3Tbu__T-FI/AAAAAAAAY4o/zY5jdHsYWnEs2NLiuzhXTZFGsP4R9vjJACHMYCw/truoc-kia-co-toa-linh-kiem-son" alt="Truyện tranh Trước Kia Có Tòa Linh Kiếm Sơn"> -->
                <span class="icon icon-hot">
                </span>
                <div class="view clearfix">
                  <span class="pull-left">
                    <i class="fa fa-eye">
                    </i> <%= manga.number_of_read %> <i class="fa fa-heart"></i> <%= manga.followers.count %>
                  </span>
                </div>
              </div>
              <figcaption>
              <h3>
              <%= link_to manga.name, manga_path(manga) %>
              </h3>
              </figcaption>
            </figure>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/mangas/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @manga.id),
             html: { method: :delete },remote: true) do |f| %>
  <%= f.submit t(".unfollow"), class: "btn" %>
    <div>
      <%= t(".followed") %> : <%= @manga.followers.count %> <%= t(".users") %>
    </div>
<% end %>

app/views/mangas/index.html.erb
<h2><%= t(".mangas") %></h2>
<div class="banner-bottom">
  <div class="container">
    <%= render @mangas %>
  </div>
</div>

app/views/mangas/show.html.erb
<div class="container">
  <div class="row">
    <div class="center-side col-md-12">
      <ul class='breadcrumb'><li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'><span itemprop='title'><%= link_to t("home"), root_path %></span></li><li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'><span itemprop='title'><%= link_to t("categories"), categories_path %></span></li><li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'><span itemprop='title'><%= link_to @manga.name, @manga %></span></li></ul>
      <article id="item-detail">
        <h1 class="title-detail"><%= @manga.name %></h1>
        <time class="small">
        <%= t(".last_updated") %> : <%= l(@manga.updated_at, format: :dmy) %>
        </time>
        <div class="detail-info">
          <div class="row">
            <div class="col-xs-4 col-image">
            </div>
            <div class="col-xs-8 col-info">
              <ul class="list-info">
                <li class="author row">
                  <p class="name col-xs-4">
                    <i class="fa fa-user">
                    </i> <%= t(".author") %>
                  </p>
                  <% if @manga.authors.nil? %>
                    <p class="col-xs-8"><%= t(".updating") %></p>
                  <% else %>
                    <p class="col-xs-8"><%= render partial: "author", collection: @authors %></p>
                  <% end %>
                </li>
                <li class="status row">
                  <p class="name col-xs-4">
                    <i class="fa fa-rss">
                    </i> <%= t(".status") %>
                  </p>
                  <p class="col-xs-8"><%= @manga.status %></p>
                </li>
                <li class="kind row">
                  <p class="name col-xs-4">
                    <i class="fa fa-tags">
                    </i> <%= t(".category") %>
                  </p>
                  <p class="col-xs-8"><%= render partial: "shared/category", collection: @categories %></p>
                </li>
                <li class="row">
                  <p class="name col-xs-4">
                    <i class="fa fa-eye">
                    </i> <%= t(".view") %>
                  </p>
                  <p class="col-xs-8"><%= @manga.number_of_read %></p>
                </li>
              </ul>
              <div class="row rating">
                <div class="col-sm-6">
                  <div class="small-2 large-2 columns">
                    <%= rating_for @manga, "rate_manga", disable_after_rate: true, readonly: true %>
                  </div><br>
                  <div class="small-2 large-4 columns">
                    <% if current_user %>
                      <%= t(".vote_now") %>: <%= rating_for @manga, "rate_manga", disable_after_rate: false, half_show: true, enable_half: true, cancel: false  %>
                    <% end %><br>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="mrt10" itemscope="" itemtype="http://schema.org/AggregateRating">
                <span itemprop="name"><%= @manga.name %> | </span>
                <%= t(".rate") %>: <span itemprop="ratingValue"><%= number_with_precision(@manga.avg_rating_dimension_rate_manga(@manga), precision: 1) %></span><meta itemprop="bestRating" content="5"><meta itemprop="worstRating" content="1">
              </div>
              <div class="follow">
                <% if user_signed_in? %>
                <div id="follow_form">
                  <% if current_user.following?(@manga) %>
                    <%= render 'unfollow' %>
                  <% else %>
                    <%= render 'follow' %>
                  <% end %>
                </div>
                <% end %>
              </div>
                <% if @chapters.present? %>
                  <div class="read-action mrt10">
                    <%= link_to t(".first_chapter"), chapter_path(@chapters.first), class: "btn btn-warning mrb5" %>
                    <%= link_to t(".last_chapter"), chapter_path(@chapters.last), class: "btn btn-warning mrb5" %>
                  </div>
                <% end %>
            </div>
          </div>
        </div>
        <div class="detail-content">
          <h3 class="list-title">
          <i class="fa fa-file-text-o">
          </i> <%= t(".detail") %>
          </h3>
          <p>  <%= @manga.detail %>
          </p>
        </div>
        <div class="list-chapter" id="nt_listchapter">
          <h2 class="list-title">
          <i class="fa fa-list">
          </i> <%= t(".list_chapters") %>
          </h2>
          <nav>
            <ul>
              <li class="row heading">
                <div class="col-xs-5 no-wrap"><%= t(".num_chapters") %></div>
                <div class="col-xs-4 no-wrap text-center"><%= t(".last_updated") %></div>
              </li>
              <%= render partial: "chapter", collection: @chapters %>
            </ul>
          </nav>
        </div>
      </article>
    </div>
  </div>
  <div class="comment">
    <%= render "shared/vote_manga" %>
  </div>
  <div class="row">
    <%= render "comments/comment_form", manga: @manga, parent_id: nil %>
    <%= comments_tree_for @supports.comments_tree.hash_tree(limit_depth: Settings.mangas.show.pages),
      @manga, @supports.comments_tree %>
  </div>
</div>