config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'
    get 'static_pages/contact'
    get "search(/:search)", to: "searches#index", as: :search
    devise_for :users, skip: :omniauth_callbacks,controller: {registrations: "registrations"}
    resources :users, only: [:show] do
      member do
        get :following
      end
    end
    resources :categories
    resources :mangas do
      resources :comments,only: [:create, :destroy]
      member do
        get :followers
      end
      resources :vote_mangas, only: [:create, :destroy]
    end
    resources :chapters do
      resources :votes,only: [:create,:destroy]
    end
    resources :authors
    resources :relationships, only: [:create, :destroy]
    namespace :admin do
      root "admin#index",as: :root
      resources :categories
      resources :mangas
      resources :chapters
      resources :animes
      resources :users do
        collection do
          post :import
        end
      end
    end
  end
  match '*.path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one :anime
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :chapters
  has_many :composes
  has_many :authors, through: :composes
  has_many :manga_categories
  has_many :categories,through: :manga_categories
  has_many :passive_relationships, class_name:  Relationship.name,
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  scope :order_manga, -> {order created_at: :desc}
  scope :most_view, -> {order number_of_read: :desc}
  scope :top_rate, -> {order average_rate: :desc}
  ratyrate_rateable "rate_manga", "rate_chapter"
  acts_as_votable
  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :poster, ThumbnailUploader

  def overall_ratings(manga)
    array = Rate.rateable
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
   def avg_rating_dimension_rate_manga(manga)
    array = Rate.rateable.dimensions
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
end

app/models/supports/manga.rb
class Supports::Manga
  attr_reader :manga, :mangas
    
  def initialize manga
    @manga = manga
  end
    
  def mangas
    @mangas ||= Manga.all
  end
    
  def comment_params
    @comment = Comment.new
  end
    
  def comments_tree
    @comments = @manga.comments
  end
end

app/controllers/admin/mangas_controller.rb
class Admin::MangasController < Admin::AdminController
  before_action :find_manga, only: [:edit, :update, :show, :destroy]
  load_and_authorize_resource

  def index
    @mangas = Manga.order_manga.paginate page: params[:page], per_page: Settings.mangas.page
  end

  def show
  end

  def new
    @manga = Manga.new
  end

  def create
    @manga = Manga.new manga_params
    if @manga.save
      flash[:info] = t("manga_created")
      redirect_to admin_mangas_path
    else
      flash[:alert] = t("manga_creating_error")
      render :new
    end
  end

  def edit
  end

  def update
    if @manga.update manga_params
      flash[:alert] = t("manga_updated")
      redirect_to admin_mangas_path
    else
      flash[:alert] = t("manga_creating_error")
      render :edit
    end
  end

  def destroy
    if @manga.destroy
      flash[:success] = t(".mangas_deleted")
      redirect_to admin_mangas_path
    else
      flash[:danger] = t(".mangas_not_deleted")
      render :index
    end
  end

  private

  def manga_params
    params.require(:manga).permit(:name, :detail, :poster,
      :poster_cache, :thumbnail, :thumbnail_cache, :country, category_ids: [])
  end

  def find_manga
    @manga = Manga.find_by id: params[:id]
    redirect_to admin_mangas_path if @manga.nil?
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :get_manga, only: [:show]

  def index
    @mangas = Manga.order_manga
    q = params[:search]
    if q
      @mangas = Manga.search(name_cont: q).result
    else
      @mangas = Manga.order_manga
    end
  end

  def show
    @chapters = @manga.chapters.order("LENGTH(name)").order(:name)
    @authors = @manga.authors.all
    @categories = @manga.categories.order(:name)
    @supports = Supports::Manga.new @manga
    @comment = Comment.new
    @comments = @manga.comments.hash_tree
    Manga.increment_counter(:number_of_read, @manga.id)
  end

  private
  def get_manga
    @manga = Manga.find_by id: params[:id]
    if @manga.nil?
      redirect_to root_url
    end
  end
end

app/helpers/manga_helper.rb
module MangaHelper
end

app/views/admin/mangas/_form.html.erb
<%= form_for [:admin, @manga] do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="block-section">
        <h3><%= t("manga_name") %></h3>
        <%= f.text_field :name, class: "form-control",
          placeholder: t("enter_manga_title") %>
      </div>
      <div class="block-section">
        <h3><%= t("manga_information") %></h3>
        <%= f.cktext_area :detail, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="block-section">
        <h3><%= t("manga_category") %></h3>
        <ul class="list-cat">
          <%= f.collection_check_boxes :category_ids,
            Category.all, :id, :name do |cate| %>
            <li>
              <%= cate.check_box %>
              <%= cate.label %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="block-section">
        <h3><%= t("Country") %></h3>
        <%= f.text_field :country, class: "form-control",
          placeholder: t("enter_manga_country") %>
      </div>
      <div class="block-section">
        <h3><%= t("manga_thumbnail") %></h3>
        <%= f.file_field :thumbnail %>
        <%= f.hidden_field :thumbnail_cache %>
        <%= image_tag @manga.thumbnail_url, class: "preview" if @manga.thumbnail? %>
        <h3><%= t("manga_poster") %></h3>
        <%= f.file_field :poster %>
        <%= f.hidden_field :poster_cache %>
        <%= image_tag @manga.poster_url, class: "preview" if @manga.poster? %>
      </div>
      <div class="block-section">
        <%= f.submit yield(:btn_title), class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/mangas/edit.html.erb
<% provide :btn_title, t("edit_manga") %>
<%= render "form" %>

app/views/admin/mangas/index.html.erb
<table class="table cat-table">
  <thead class="thead-dark">
  <tr>
    <th scope="col" >#</th>
    <th scope="col" ><%= t("name") %></th>
    <th scope="col" ><%= t("category") %></th>
    <th scope="col" ><%= t("action") %></th>
  </tr>
  </thead>
  <tbody>
  <% @mangas.each.with_index(1) do |manga, index| %>
    <tr>
      <td><%= index %></td>
      <td><%= manga.name %></td>
      <td>
        <% manga.categories.each do |cat| %>
          <%= link_to cat.name, admin_category_path(cat) %>
        <% end %>
      </td>
      <td>
        <%= link_to t(".edit"), edit_admin_manga_path(manga) %> |
        <%= link_to t(".delete"), admin_manga_path(manga.id), method: :delete,
              data: { confirm: t("confim") } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @mangas %>

app/views/admin/mangas/new.html.erb
<% provide(:btn_title, t("add_manga")) %>
<%= render "form" %>

app/views/admin/mangas/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="block-section">
      <h3><%= t("name") %></h3>
      <%= @manga.name %>
    </div>
  </div>
</div>