config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'
    get 'static_pages/contact'
    get "search(/:search)", to: "searches#index", as: :search
    devise_for :users, skip: :omniauth_callbacks,controller: {registrations: "registrations"}
    resources :users, only: [:show] do
      member do
        get :following
      end
    end
    resources :categories
    resources :mangas do
      resources :comments,only: [:create, :destroy]
      member do
        get :followers
      end
      resources :vote_mangas, only: [:create, :destroy]
    end
    resources :chapters do
      resources :votes,only: [:create,:destroy]
    end
    resources :authors
    resources :relationships, only: [:create, :destroy]
    namespace :admin do
      root "admin#index",as: :root
      resources :categories
      resources :mangas
      resources :chapters
      resources :animes
      resources :users do
        collection do
          post :import
        end
      end
    end
  end
  match '*.path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, controller_namespace)
    user ||= User.new
    case controller_namespace
      when 'Admin'
        can :manage, :all if user.admin?
      else
        can :read, :all
        can :update, User,id: user.id
      end
  end
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :manga
  mount_uploader :video_thumbnail, ThumbnailUploader
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :composes
  has_many :mangas, through: :composes
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :manga_categories
  has_many :mangas, through: :manga_categories
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :manga
  acts_as_votable

  mount_uploader :images, ThumbnailUploader

  scope :next_chapter, -> (id){
    where("id > ?", id).order(id: :asc)
  }

  scope :previous_chapter, -> (id){
    where("id < ?", id).order(id: :desc)
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  
  validates :user, presence: true
  validates :content, presence: true
  
  acts_as_tree order: "created_at ASC"
end

app/models/compose.rb
class Compose < ApplicationRecord
  belongs_to :author
  belongs_to :manga
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :manga
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one :anime
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :chapters
  has_many :composes
  has_many :authors, through: :composes
  has_many :manga_categories
  has_many :categories,through: :manga_categories
  has_many :passive_relationships, class_name:  Relationship.name,
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  scope :order_manga, -> {order created_at: :desc}
  scope :most_view, -> {order number_of_read: :desc}
  scope :top_rate, -> {order average_rate: :desc}
  ratyrate_rateable "rate_manga", "rate_chapter"
  acts_as_votable
  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :poster, ThumbnailUploader

  def overall_ratings(manga)
    array = Rate.rateable
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
   def avg_rating_dimension_rate_manga(manga)
    array = Rate.rateable.dimensions
    stars = array.map {|manga| manga.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
end

app/models/manga_category.rb
class MangaCategory < ApplicationRecord
  belongs_to :manga
  belongs_to :category
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

  #attr_accessible :rate, :dimension
  scope :rateable, ->{where(rateable_id: ids, rateable_type: 'manga')}
  scope :dimensions, ->{where(dimension: "rate_manga")}

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: Manga.name
  validates_presence_of :follower_id
  validates_presence_of :followed_id
end

app/models/user.rb
class User < ApplicationRecord
  require "csv"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  enum role: {user: 0, admin: 1}
  after_initialize :set_default_role, if: :new_record?
  ratyrate_rater
  acts_as_voter

  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :active_relationships, class_name: Relationship.name,
            foreign_key: "follower_id",
            dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  scope :load_data, -> {select(:id, :name, :email, :role)}

  validates_presence_of :name

  def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do | user |
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def to_csv
    attributes = %w(id name email roles)
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.find_each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end

  def import(file)
    error_row = []
    index = 0
    CSV.foreach(file.path, headers: :true) do |row|
      user = User.new row.to_hash.merge(password: "12345678")
      index += 1
      unless user.save
        error_row << index
      end
    end
    error_row.join ", "
  end

  def follow(manga)
    following << manga
  end

  def unfollow(manga)
    following.delete(manga)
  end

  def following?(manga)
    following.include?(manga)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/manga_helper.rb
module MangaHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/admin/admin/index.html.erb
<div class="content-wrapper">
  <div class="container-fluid">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t("Dashboard"),admin_root_url %>
      </li>
      <li class="breadcrumb-item active"><%= t("my_dashboard") %></li>
    </ol>
    <div class="row">
      <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-users"></i>
          </div>
          <div class="mr-5"><%= User.all.size %></div>
        </div>
          <a class="card-footer text-white clearfix small z-1" href="/en/admin/users">
            <span class="float-left"><%= t("all_employee") %></span>
            <span class="float-right">
             <i class="fa fa-angle-right"></i>
            </span>
          </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-warning o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-list"></i>
          </div>
          <div class="mr-5"><%= User.all.size %></div>
        </div>
          <%= link_to admin_users_path,class: "card-footer text-white clearfix small z-1" do %><%= t("all_divisions") %>
            <span class="float-left"></span>
            <span class="float-right">
              <i class="fa fa-angle-right"></i>
            </span>
          <% end %>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-institution"></i>
          </div>
          <div class="mr-5"><%= User.all.size %></div>
        </div>
          <%= link_to admin_users_path,class: "card-footer text-white clearfix small z-1" do %><%= t("all_positions") %>
            <span class="float-left"></span>
            <span class="float-right">
              <i class="fa fa-angle-right"></i>
            </span>
          <% end %>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-support"></i>
          </div>
          <div class="mr-5"><%= User.all.size %></div>
          <%= link_to admin_users_path,class: "card-footer text-white clearfix small z-1" do %><%= t("all_reports") %>
            <span class="float-left"></span>
            <span class="float-right">
              <i class="fa fa-angle-right"></i>
            </span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header text-center">
        <%= t("skill_chart") %>
      </div>
      <div class="card-content">
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_admin_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © MAMS 2018</small>
    </div>
  </div>
</footer>

app/views/layouts/admin/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <%= link_to "Admin Report System", "#" , class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
          <%= link_to admin_root_path , class: "nav-link" do %>
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text"><%= t("dashboard") %></span>
          <% end %>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Charts">
          <%= link_to "#", class: "nav-link" do %>
            <i class="fa fa-fw fa-area-chart"></i>
            <span class="nav-link-text">Charts</span>
          <% end %>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Tables">
          <%= link_to "#", class: "nav-link" do %>
            <i class="fa fa-fw fa-table"></i>
            <span class="nav-link-text">Tables</span>
          <% end %>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Manager">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-wrench"></i>
            <span class="nav-link-text"><%= (t"Manager") %></span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseComponents">
            <li><%= link_to t(:manager_category), admin_categories_path %></li>
            <li><%= link_to t(:manager_manga), admin_mangas_path %></li>
            <li><%= link_to t(:manager_chapter), admin_chapters_path %></li>
            <li><%= link_to t(:manager_anime), admin_animes_path %></li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Manager User">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text"><%= t("manager_user") %></span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseExamplePages">
            <li><%= link_to t(:user_detail), admin_users_url %></li>
            <li><%= link_to t(:user_division), "#" %></li>
            <li><%= link_to t(:user_position), "#" %></li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-sitemap"></i>
            <span class="nav-link-text">Menu Levels</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li><a href="navbar.html">Navbar</a></li>
            <li><a href="navbar.html">Navbar</a></li>
            <li><a href="navbar.html">Navbar</a></li>
            <li>
              <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
              <ul class="sidenav-third-level collapse" id="collapseMulti2">
                <li><a href="navbar.html">Navbar</a></li>
                <li><a href="navbar.html">Navbar</a></li>
                <li><a href="navbar.html">Navbar</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Link">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-link"></i>
            <span class="nav-link-text">Link</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-envelope"></i>
            <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
            <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">New Messages:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all messages</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell"></i>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">New Alerts:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong><i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong><i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all alerts</a>
          </div>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" >
              <i class="fa fa-fw fa-user-secret"></i><%= t(".account") %></a>
              <div class="dropdown-menu">
                <%= link_to "#", class: "dropdown-item" do %>
                 <i class="fa fa-fw fa-user"></i><%= t(".profile") %>
                <% end %>
                <%= link_to "#", class: "dropdown-item" do %>
                 <i class="fa fa-fw fa-cog"></i><%= t(".setting") %>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                 <i class="fa fa-fw fa-sign-out"></i><%= t(".log_out") %>
                <% end %>
              </div>
        </li>
      </ul>
    </div>
</nav>

app/views/shared/_category.html.erb
<%= link_to category.name, category_path(category) %>

app/views/shared/_manga.html.erb
<div class="container">
  <div class="row">
    <div class="center-side col-md-8">
      <div class="items">
        <div class="row">
          <div class="item">
            <figure class="clearfix">
              <div class="image">
                <!-- <img src="//st.nettruyen.com/Data/logos/logo-nettruyen.png" class="lazy" data-original="https://3.bp.blogspot.com/-U9YzPttwuiA/W3Tbu__T-FI/AAAAAAAAY4o/zY5jdHsYWnEs2NLiuzhXTZFGsP4R9vjJACHMYCw/truoc-kia-co-toa-linh-kiem-son" alt="Truyện tranh Trước Kia Có Tòa Linh Kiếm Sơn"> -->
                <span class="icon icon-hot">
                </span>
                <div class="view clearfix">
                  <span class="pull-left">
                    <i class="fa fa-eye">
                    </i> <%= manga.number_of_read %> <i class="fa fa-heart"></i> <%= manga.followers.count %>
                  </span>
                </div>
              </div>
              <figcaption>
              <h3>
              <%= link_to manga.name, manga_path(manga) %>
              </h3>
              </figcaption>
            </figure>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_vote_form_chapter.html.erb
<div id="vote_form">
  <% if user_signed_in? %>
    <% if (current_user.voted_down_on? @chapter) || (!ActsAsVotable::Vote.where(voter_id: current_user,votable_id: @chapter.id).present?) %>
      <%= link_to chapter_votes_path(@chapter), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
      <% end %>
    <% else %>
      <%= link_to chapter_vote_path(@chapter,0), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart"></span>
      <% end %>
    <% end %>
  <% end %>
  <%= t "chapters.show.like" %> <%= @chapter.get_upvotes.size %>
  <%= raw @chapter.votes_for.up.by_type(User).voters.map { |voter| link_to voter.name, "#" }.join(', ') %>
</div>

app/views/shared/_vote_manga.html.erb
<div id="vote_form1">
  <% if user_signed_in? %>
    <% if (current_user.voted_down_on? @manga) || (!ActsAsVotable::Vote.where(voter_id: current_user,votable_id: @manga.id).present?) %>
      <%= link_to manga_vote_mangas_path(@manga), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
      <% end %>
    <% else %>
      <%= link_to manga_vote_manga_path(@manga,0), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart"></span>
      <% end %>
    <% end %>
  <% end %>
  <%= t "mangas.show.like" %> <%= @manga.get_upvotes.size %>
  <%= raw @manga.votes_for.up.by_type(User).voters.map { |voter| link_to voter.name, "#" }.join(', ') %>
</div>