config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'
    get 'static_pages/contact'
    get "search(/:search)", to: "searches#index", as: :search
    devise_for :users, skip: :omniauth_callbacks,controller: {registrations: "registrations"}
    resources :users, only: [:show] do
      member do
        get :following
      end
    end
    resources :categories
    resources :mangas do
      resources :comments,only: [:create, :destroy]
      member do
        get :followers
      end
      resources :vote_mangas, only: [:create, :destroy]
    end
    resources :chapters do
      resources :votes,only: [:create,:destroy]
    end
    resources :authors
    resources :relationships, only: [:create, :destroy]
    namespace :admin do
      root "admin#index",as: :root
      resources :categories
      resources :mangas
      resources :chapters
      resources :animes
      resources :users do
        collection do
          post :import
        end
      end
    end
  end
  match '*.path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :manga
  acts_as_votable

  mount_uploader :images, ThumbnailUploader

  scope :next_chapter, -> (id){
    where("id > ?", id).order(id: :asc)
  }

  scope :previous_chapter, -> (id){
    where("id < ?", id).order(id: :desc)
  }
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < Admin::AdminController
  before_action :find_chapter, only: [:edit, :update, :show, :destroy]
  load_and_authorize_resource

  def index
    @chapters = Chapter.paginate page: params[:page], per_page: Settings.chapters.page
  end
  def show
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new chapter_params
    if @chapter.save
      flash[:info] = t("chapter_created")
      redirect_to admin_chapters_path
    else
      flash[:alert] = t("chapter_creating_error")
      render :new
    end
  end

  def edit
  end

  def update
    if @chapter.update chapter_params
      flash[:alert] = t("chapter_updated")
      redirect_to admin_chapters_path
    else
      flash[:alert] = t("chapter_creating_error")
      render :edit
    end
  end

  def destroy
    if @chapter.destroy
      flash[:success] = t(".chapters_deleted")
      redirect_to admin_chapters_path
    else
      flash[:danger] = t(".chapters_not_deleted")
      render :index
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:id, :name, :images, :images_cache, :manga_id, :content)
  end

  def find_chapter
    @chapter =Chapter.find_by id: params[:id]
    redirect_to admin_chapters_path if @chapter.nil?
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :get_chapter, only: [:show]

  def show
    @chapters = @chapter.manga.chapters.order("LENGTH(name)").order(:name)
    @previous = @chapters.previous_chapter(@chapter.id).first
    @next = @chapters.next_chapter(@chapter.id).first
  end

  private
  def get_chapter
    @chapter = Chapter.find_by id: params[:id]
    if @chapter.nil?
      redirect_to root_url
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/admin/chapters/_form_chapter.html.erb
<%= form_for [:admin, @chapter] do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="block-section">
        <h3><%= t("manga_name") %></h3>
        <%= f.text_field :name, class: "form-control",
          placeholder: t("enter_chapter_number") %>
      </div>
      <div class="block-section">
        <h3><%= t("manga_information") %></h3>
        <%= f.cktext_area :content, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="block-section">
        <h3><%= t("manga_category") %></h3>
        <ul class="list-cat">
          <%= f.collection_select :manga_id,
            Manga.all, :id, :name %>
        </ul>
      </div>
      <div class="block-section">
        <h3><%= t("chapter_thumbnail") %></h3>
        <%= f.file_field :images %>
        <%= f.hidden_field :images_cache %>
        <%= image_tag @chapter.images_url, class: "preview" if @chapter.images? %>
      </div>
      <div class="block-section">
        <%= f.submit yield(:btn_title), class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/chapters/edit.html.erb
<%= render "form_chapter" %>

app/views/admin/chapters/index.html.erb
<table class="table cat-table">
  <thead class="thead-dark">
  <tr>
    <th scope="col" >#</th>
    <th scope="col" ><%= t("name") %></th>
    <th scope="col" ><%= t(".manga_name") %></th>
    <th scope="col" ><%= t(".action") %></th>
  </tr>
  </thead>
  <tbody>
    <% @chapters.each.with_index(1) do |chapter, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= chapter.name %></td>
        <td>
          <%= link_to chapter.manga.name, admin_manga_path(chapter) %>
        </td>
        <td>
          <%= link_to t(".edit"), edit_admin_chapter_path(chapter) %> |
          <%= link_to t(".delete"), admin_chapter_path(chapter.id), method: :delete,
                data: { confirm: t("confim") } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @chapters %>
<%= link_to t("create"), new_admin_chapter_path, class: "btn btn success" %>

app/views/admin/chapters/new.html.erb
<%= render "form_chapter" %>